# Generated by Django 5.2.3 on 2025-07-07 21:25

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_folhaponto_motivo_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folhaponto',
            name='motivo_status',
        ),
        migrations.AlterField(
            model_name='codigoocorrencia',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidades_gerenciadas',
            field=models.ManyToManyField(blank=True, help_text='Selecione as unidades pelas quais este usuário pode ser responsável (para Agentes de Pessoal).', to='core.unidade', verbose_name='Unidades Gerenciadas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
